CONFIG_ZMK_RGB_UNDERGLOW=y
# nice_nano//zmk board overlay defines zmk,ext-power-generic on GPIO0 13 (LED power switch)
# EXT_POWER=y lets ZMK enable that switch when underglow is active
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
